import type { LucideIcon } from 'lucide-react';
import {
  Armchair,
  ArrowDownToLine,
  ArrowUpToLine,
  Baby,
  BedDouble,
  Bell,
  BookOpen,
  Briefcase,
  Brush,
  CakeSlice,
  CalendarDays,
  CalendarX2,
  Camera,
  Car,
  Check,
  ChevronDown,
  Church,
  CircleCheckBig,
  Clapperboard,
  Clock,
  Coffee,
  Contact,
  Croissant,
  Dog,
  Fence,
  FileDown,
  FileText,
  Flag,
  Flower2,
  Gem,
  Gift,
  Globe,
  HandHeart,
  HandPlatter,
  Heart,
  House,
  IceCreamCone,
  Image,
  ImagePlus,
  Lightbulb,
  Link2,
  ListChecks,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Martini,
  Menu,
  Music,
  Palette,
  Paperclip,
  PartyPopper,
  Pencil,
  Phone,
  Plane,
  Plus,
  Receipt,
  RefreshCw,
  RotateCcw,
  Salad,
  Scissors,
  Search,
  Settings,
  Sheet,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smile,
  Sparkles,
  SprayCan,
  Star,
  Stethoscope,
  Store,
  Table,
  Ticket,
  Trash2,
  TreePine,
  TriangleAlert,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  WashingMachine,
  Watch,
  Wine,
  X,
} from 'lucide-react';

/**
 * App icon id → Lucide component.
 *
 * The ids are Material Symbols names and are kept deliberately: they are
 * persisted in user plans (`icon?` on vendors/tasks/shopping/seserahan), synced
 * to Firestore and written into JSON backups, so renaming them would orphan
 * every icon a user has already chosen. This map is the only place the two
 * vocabularies meet — everything else in the app speaks these ids.
 *
 * `satisfies` keeps the values checked as real Lucide components while letting
 * `IconName` stay a literal union of the keys.
 */
export const ICON_MAP = {
  // --- navigation & chrome ---
  timeline: CalendarDays,
  storefront: Store,
  account_balance_wallet: Wallet,
  checklist: ListChecks,
  shopping_bag: ShoppingBag,
  card_giftcard: Gift,
  contacts: Contact,
  summarize: FileText,
  settings: Settings,
  menu: Menu,
  search: Search,
  notifications: Bell,
  expand_more: ChevronDown,

  // --- actions ---
  add: Plus,
  edit: Pencil,
  close: X,
  check: Check,
  check_circle: CircleCheckBig,
  delete: Trash2,
  delete_forever: Trash2,
  download: ArrowDownToLine,
  upload: ArrowUpToLine,
  refresh: RefreshCw,
  restore: RotateCcw,
  link: Link2,
  public: Globe,
  login: LogIn,
  logout: LogOut,
  group_add: Users,
  attach_file: Paperclip,
  image: Image,
  add_photo_alternate: ImagePlus,
  picture_as_pdf: FileDown,
  table_view: Sheet,
  warning: TriangleAlert,
  schedule: Clock,
  event_busy: CalendarX2,

  // --- venue ---
  location_on: MapPin,
  home: House,
  church: Church,
  celebration: PartyPopper,
  local_florist: Flower2,
  chair: Armchair,
  lightbulb: Lightbulb,
  table_restaurant: Table,
  deck: Fence,
  park: TreePine,

  // --- food ---
  restaurant: Utensils,
  lunch_dining: Salad,
  cake: CakeSlice,
  local_bar: Martini,
  local_cafe: Coffee,
  icecream: IceCreamCone,
  bakery_dining: Croissant,
  set_meal: HandPlatter,
  dinner_dining: Utensils,
  liquor: Wine,

  // --- attire & beauty ---
  checkroom: Shirt,
  spa: Sparkles,
  diamond: Gem,
  content_cut: Scissors,
  watch: Watch,
  face: Smile,
  brush: Brush,
  dry_cleaning: WashingMachine,
  iron: Shirt,
  shopping_basket: ShoppingBasket,

  // --- gifts ---
  redeem: Ticket,
  favorite: Heart,
  shopping_cart: ShoppingCart,
  volunteer_activism: HandHeart,
  local_mall: ShoppingBag,
  toys: Baby,
  auto_awesome: Sparkles,
  star: Star,

  // --- planning ---
  event_note: CalendarDays,
  mail: Mail,
  auto_stories: BookOpen,
  photo_camera: Camera,
  music_note: Music,
  work: Briefcase,
  receipt_long: Receipt,
  description: FileText,
  groups: Users,
  call: Phone,
  movie: Clapperboard,

  // --- other ---
  directions_car: Car,
  flight: Plane,
  hotel: BedDouble,
  palette: Palette,
  umbrella: Umbrella,
  pets: Dog,
  stroller: Baby,
  medical_services: Stethoscope,
  cleaning_services: SprayCan,
  flag: Flag,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_MAP;

/** Drawn for an id we do not recognize — matches `iconForCategory`'s fallback. */
export const FALLBACK_ICON: LucideIcon = Flag;
